[app]

# ---------------------------------------------------------------------------
# Rln for Android — buildozer configuration
#
# This packages the phone-first Kivy front-end (android/main.py) together with
# the Rln command engine (the `commands` and `rln_io` packages, copied beside
# main.py by build_apk.sh before the build).
#
# Scope: data IO, exploration, transforms, econometrics, panel/DiD, diagnostics,
# charts, scripting, and LRTM. NLP/transformer/translation are excluded from the
# Android dependency set on purpose.
# ---------------------------------------------------------------------------

title = Rln
package.name = rln
package.domain = io.github.akirawisnu

# Launcher icon: striped "Rln" wordmark, blue on white (staged beside the spec
# by build_apk.sh; generated by android/_make_icon.py).
icon.filename = ./icon.png

source.dir = .
source.main = main.py

# Bundle Python sources plus example datasets, scripts, and docs the engine may
# open. NOTE: the example *scripts* are .do / .rln files — they MUST be listed
# here or buildozer silently drops them and the in-app examples show data files
# with no scripts to run.
source.include_exts = py,png,jpg,jpeg,csv,dta,parquet,txt,md,json,do,rln
# Keep the build lean: drop the desktop-only / build-only trees if present.
source.exclude_dirs = bin,.buildozer,__pycache__,tests,packaging,gui,hf_models,argos_models,dist,build

version = 1.2.8

# ---------------------------------------------------------------------------
# Python requirements
#
# Ships the modern scientific stack Rln was built against (numpy 2.x, pandas,
# scipy, matplotlib from the p4a `develop` recipes), plus polars for LRTM and
# a from-source statsmodels (see p4a-recipes/statsmodels).
#
# Deliberately NOT shipped, and why it's safe:
#   * pyarrow  — no usable aarch64-Android wheel (Apache Arrow C++). Rln avoids
#                it: polars reads parquet natively and LRTM converts to pandas
#                via to_numpy(), not polars.to_pandas() (which needs pyarrow).
#                See commands/lrtm.py:_pl_to_pandas and rln_io/_load_parquet.
#   * linearmodels / diff-diff — heavy; ivregress, panel RE and the advanced
#                didregress estimators report "needs desktop" at runtime.
#   * rapidfuzz / polyfuzz, pyreadr, dbfread, NLP stack — optional; the
#                relevant commands degrade with a clear message.
#
# IMPORTANT: statsmodels is listed below, but if its recipe ever fails to load
# on-device the engine does NOT break — commands/stats_fallback.py provides a
# validated NumPy/SciPy backend (regress/logit/probit/poisson + diagnostics +
# xtreg-FE + DiD-TWFE) that _check_statsmodels() switches to automatically.
#
# All heavy libs are imported lazily inside the relevant commands, so their
# absence never breaks app startup.
# ---------------------------------------------------------------------------
requirements = python3,kivy,pillow,rich,numpy,pandas,scipy,matplotlib,python-dateutil,pytz,packaging,setuptools,polars,openpyxl,xlrd,et-xmlfile,pygments,patsy,statsmodels

orientation = portrait
fullscreen = 0

# Storage permissions so the user can open data files from shared storage.
# MANAGE_EXTERNAL_STORAGE ("All files access") is what actually lets the app
# read arbitrary .csv/.dta/.do/.parquet files on Android 11+ (scoped storage
# neuters plain READ_EXTERNAL_STORAGE for non-media files). The app routes the
# user to the system grant screen on first Open.
android.permissions = READ_EXTERNAL_STORAGE,WRITE_EXTERNAL_STORAGE,MANAGE_EXTERNAL_STORAGE

# Target a 64-bit-only device profile (modern phones). Add armeabi-v7a only if
# you need older 32-bit hardware (roughly doubles build time).
android.archs = arm64-v8a

android.api = 33
android.minapi = 24
android.ndk_api = 24

# Let buildozer manage SDK/NDK download on first run.
android.accept_sdk_license = True

# Use the p4a `develop` branch — it carries the modern Meson-based recipes for
# the scientific stack (numpy 2.x, pandas 2.3.0, scipy, matplotlib) that match
# Rln's desktop dependencies. Its only defect for us was that it defaults to
# Python 3.14, which has no kiwisolver/scientific wheels yet (the build failed
# at kiwisolver==1.4.5). We fix that below by pinning Python to 3.11.
p4a.branch = develop

# Local recipe overrides live here. We override python3 + hostpython3 to pin
# CPython 3.11 (instead of develop's default 3.14). The statsmodels recipe also
# lives here but is unused until it is re-added to `requirements` in Phase 2.
# build_apk.sh copies this tree next to the spec before building.
p4a.local_recipes = ./p4a-recipes

[buildozer]

log_level = 2
warn_on_root = 1
